name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Adjust this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Adjust based on your Java version
          distribution: 'temurin'  # Use a valid distribution

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Convert repository name to lowercase
        id: convert_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ env.REPO_NAME }}/java-app:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ env.REPO_NAME }}/java-app:latest
